package configimport

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/chasebank87/PourOver/internal/config"
)

// FormatMacOSLua renders a macos.lua module from MacOSDefaults.
// The module returns { defaults = { … } } for pourover.lua `macos = require("macos")`.
func FormatMacOSLua(d config.MacOSDefaults) string {
	var b strings.Builder
	b.WriteString("-- generated by pourover import macos\n")
	b.WriteString("return {\n")
	b.WriteString("  defaults = {\n")

	for _, section := range sortedMapKeys(d.Sections) {
		keys := d.Sections[section]
		fmt.Fprintf(&b, "    %s = {\n", luaTableKey(section))
		for _, key := range sortedSettingKeys(keys) {
			fmt.Fprintf(&b, "      %s = %s,\n", luaTableKey(key), formatSettingValue(keys[key]))
		}
		b.WriteString("    },\n")
	}

	if len(d.Custom) > 0 {
		b.WriteString("    custom = {\n")
		for _, domain := range sortedMapKeys(d.Custom) {
			keys := d.Custom[domain]
			fmt.Fprintf(&b, "      %s = {\n", luaTableKey(domain))
			for _, key := range sortedSettingKeys(keys) {
				fmt.Fprintf(&b, "        %s = %s,\n", luaTableKey(key), formatSettingValue(keys[key]))
			}
			b.WriteString("      },\n")
		}
		b.WriteString("    },\n")
	}

	b.WriteString("  },\n")
	b.WriteString("}\n")
	return b.String()
}

// MergeMacOSDefaults merges discovered curated defaults into existing.
// When force is false, only missing keys are added (existing values win).
// When force is true, curated Sections are replaced by discovered.Sections;
// existing Custom is always preserved. Returns the count of keys taken from discovered.
func MergeMacOSDefaults(existing, discovered config.MacOSDefaults, force bool) (config.MacOSDefaults, int) {
	merged := config.MacOSDefaults{
		Custom: cloneSettingsTree(existing.Custom),
	}
	added := 0

	if force {
		merged.Sections = cloneSettingsTree(discovered.Sections)
		for _, keys := range discovered.Sections {
			added += len(keys)
		}
		return merged, added
	}

	merged.Sections = cloneSettingsTree(existing.Sections)
	if merged.Sections == nil {
		merged.Sections = make(map[string]map[string]config.SettingValue)
	}
	for section, discKeys := range discovered.Sections {
		if merged.Sections[section] == nil {
			merged.Sections[section] = make(map[string]config.SettingValue)
		}
		for key, val := range discKeys {
			if _, ok := merged.Sections[section][key]; ok {
				continue
			}
			merged.Sections[section][key] = val
			added++
		}
	}
	return merged, added
}

func formatSettingValue(v config.SettingValue) string {
	switch v.Kind {
	case config.SettingBool:
		if v.Bool {
			return "true"
		}
		return "false"
	case config.SettingInt:
		return strconv.FormatInt(v.Int, 10)
	case config.SettingFloat:
		return strconv.FormatFloat(v.Float, 'g', -1, 64)
	case config.SettingString:
		return strconv.Quote(v.String)
	case config.SettingArray:
		if len(v.Array) == 0 {
			return "{}"
		}
		var b strings.Builder
		b.WriteString("{\n")
		for _, s := range v.Array {
			fmt.Fprintf(&b, "        %s,\n", strconv.Quote(s))
		}
		b.WriteString("      }")
		return b.String()
	default:
		return "nil"
	}
}

func luaTableKey(name string) string {
	if isLuaIdent(name) {
		return name
	}
	return fmt.Sprintf("[%q]", name)
}

func isLuaIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		ok := r == '_' || r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z' || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return false
		}
	}
	return true
}

func sortedMapKeys(m map[string]map[string]config.SettingValue) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedSettingKeys(m map[string]config.SettingValue) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func cloneSettingsTree(in map[string]map[string]config.SettingValue) map[string]map[string]config.SettingValue {
	if in == nil {
		return nil
	}
	out := make(map[string]map[string]config.SettingValue, len(in))
	for domain, keys := range in {
		cp := make(map[string]config.SettingValue, len(keys))
		for k, v := range keys {
			if v.Kind == config.SettingArray && v.Array != nil {
				v.Array = append([]string(nil), v.Array...)
			}
			cp[k] = v
		}
		out[domain] = cp
	}
	return out
}
