package configimport

import (
	"fmt"
	"sort"
	"strings"
)

// FormatPackagesLua renders a packages.lua module from formula and cask lists.
func FormatPackagesLua(formulae, casks []string) string {
	formulae = sortedCopy(formulae)
	casks = sortedCopy(casks)
	var b strings.Builder
	b.WriteString("-- Homebrew packages declared for PourOver (generated by pourover import).\n")
	b.WriteString("return {\n")
	b.WriteString("  formulae = {\n")
	for _, name := range formulae {
		fmt.Fprintf(&b, "    %q,\n", name)
	}
	b.WriteString("  },\n")
	b.WriteString("  casks = {\n")
	for _, name := range casks {
		fmt.Fprintf(&b, "    %q,\n", name)
	}
	b.WriteString("  },\n")
	b.WriteString("}\n")
	return b.String()
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
