package configimport

import (
	"fmt"
	"sort"
	"strings"

	"github.com/chasebank87/PourOver/internal/config"
)

// FormatPackagesLua renders a packages.lua module from formula and cask lists
// (empty taps section, no mas). Prefer FormatPackagesLuaFull when taps/mas are known.
func FormatPackagesLua(formulae, casks []string) string {
	return FormatPackagesLuaFull(nil, formulae, casks, nil)
}

// FormatPackagesLuaFull renders packages.lua including taps and optional mas.
// A nil mas slice omits the mas key (unmanaged). A non-nil slice (including empty)
// emits mas = { ... } so the next load treats MAS as configured.
func FormatPackagesLuaFull(taps, formulae, casks []string, mas []config.MasApp) string {
	taps = sortedCopy(taps)
	formulae = sortedCopy(formulae)
	casks = sortedCopy(casks)
	var b strings.Builder
	b.WriteString("-- Homebrew packages declared for PourOver (generated by pourover import).\n")
	b.WriteString("return {\n")
	b.WriteString("  taps = {\n")
	for _, name := range taps {
		fmt.Fprintf(&b, "    %q,\n", name)
	}
	b.WriteString("  },\n")
	b.WriteString("  formulae = {\n")
	for _, name := range formulae {
		fmt.Fprintf(&b, "    %q,\n", name)
	}
	b.WriteString("  },\n")
	b.WriteString("  casks = {\n")
	for _, name := range casks {
		fmt.Fprintf(&b, "    %q,\n", name)
	}
	b.WriteString("  },\n")
	if mas != nil {
		mas = sortedMasCopy(mas)
		b.WriteString("  mas = {\n")
		for _, app := range mas {
			fmt.Fprintf(&b, "    %s = %d,\n", luaTableKey(app.Name), app.ID)
		}
		b.WriteString("  },\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// FormatPackagesLuaFullWithAutoUpdate is FormatPackagesLuaFull plus a preserved
// packages.auto_update section when that key is managed in the current manifest.
func FormatPackagesLuaFullWithAutoUpdate(taps, formulae, casks []string, mas []config.MasApp, auto config.AutoUpdate) string {
	body := FormatPackagesLuaFull(taps, formulae, casks, mas)
	if !auto.Configured {
		return body
	}
	return strings.TrimSuffix(body, "}\n") + formatAutoUpdateLua(auto) + "}\n"
}

func formatAutoUpdateLua(auto config.AutoUpdate) string {
	simple := auto.Interval == "" && !auto.Upgrade && !auto.Greedy && !auto.Cleanup && !auto.Immediate
	if simple {
		if auto.Enable {
			return "  auto_update = true,\n"
		}
		return "  auto_update = false,\n"
	}
	var b strings.Builder
	b.WriteString("  auto_update = {\n")
	fmt.Fprintf(&b, "    enable = %v,\n", auto.Enable)
	if auto.Interval != "" {
		fmt.Fprintf(&b, "    interval = %q,\n", auto.Interval)
	}
	if auto.Upgrade {
		b.WriteString("    upgrade = true,\n")
	}
	if auto.Greedy {
		b.WriteString("    greedy = true,\n")
	}
	if auto.Cleanup {
		b.WriteString("    cleanup = true,\n")
	}
	if auto.Immediate {
		b.WriteString("    immediate = true,\n")
	}
	b.WriteString("  },\n")
	return b.String()
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

func sortedMasCopy(in []config.MasApp) []config.MasApp {
	out := append([]config.MasApp(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		return out[i].ID < out[j].ID
	})
	return out
}
