package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadMacOSModule_SectionsAndCustom(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "macos.lua")
	src := `-- generated by pourover import macos
return {
  defaults = {
    dock = {
      autohide = true,
      tilesize = 48,
    },
    custom = {
      ["com.apple.Safari"] = {
        ShowFullURLInSmartSearchField = true,
      },
    },
  },
}
`
	if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := LoadMacOSModule(path)
	if err != nil {
		t.Fatal(err)
	}
	if !got.Sections["dock"]["autohide"].Bool {
		t.Fatalf("autohide = %#v", got.Sections["dock"]["autohide"])
	}
	if got.Sections["dock"]["tilesize"].Int != 48 {
		t.Fatalf("tilesize = %#v", got.Sections["dock"]["tilesize"])
	}
	if !got.Custom["com.apple.Safari"]["ShowFullURLInSmartSearchField"].Bool {
		t.Fatalf("custom = %#v", got.Custom)
	}
}
